### PR TITLE
Update Master

### PR DESCRIPTION
**Pull request by iksaku**
From mobile... So I need to create a pull request :P

### CODE REVIEW

**Comment by PEMapModder** [comment]
Use command line next time to prevent creation of merge commits.

**Comment by iksaku** [comment]
@PEMapModder As I told... I'm on mobile, this was the only way :$

**Comment by PEMapModder** [comment]
Then don't merge it! Now our master branch is no longer parallel with PocketMine master branch, and all our future new branches will have one extra commits, which will be a reason for the PocketMine team not to merge the pull requests.

**Comment by iksaku** [comment]
I had fixed the commit problem, later today I will fix other issue with that commit on a "secret branch" ;)

**Comment by iksaku** [comment]
@PEMapModder BTW: We can always squash commits ;)

**Pull request merged**
